import java.util.*;
class Example{
	public static void main(String args[]){
		Scanner input=new Scanner(System.in);
		System.out.println("===============================================================================================================================================");
		System.out.println("||                                                           @@@@@@@@@@@@@@@@                                                                ||");
		System.out.println("||                                                        @@@@@@@@@@@@@@@@@@@@@@                                                             ||");
		System.out.println("||                                                       @@@@@@@@@@@@@@@@@@@@@@@@                                                            ||");
		System.out.println("||                                                      @@@@        @@        @@@@                                                           ||");
		System.out.println("||                                                      @@@         @@         @@@                                                           ||");
		System.out.println("||                                                      @@@         @@         @@@                                                           ||");
		System.out.println("||                                                      @@@@@@@@@@@@@@@@@@@@@@@@@@                                                           ||");
		System.out.println("||                                                      @@@@@@@@@@@@@@@@@@@@@@@@@@                                                           ||");
		System.out.println("||                                                      @@@@@@@@@@@@@@@@@@@@@@@@@@                                                           ||");
		System.out.println("||                                                      @@@  @@@@@@@@@@@@@@@@  @@@                                                           ||");
		System.out.println("||                                                      @@     @@@@@@@@@@@@     @@                                                           ||");
		System.out.println("||                                                      @@@@@@@@@@@@@@@@@@@@@@@@@@                                                           ||");
		System.out.println("||                                                        @@@@@@@@@@@@@@@@@@@@@@                                                             ||");
		System.out.println("||                                                                                                                                           ||");
		System.out.println("||                                                         @@@@            @@@@                                                              ||");
		System.out.println("||                                                       @@@@@@@@@@@@@@@@@@@@@@@@                                                            ||");
		System.out.println("||                                                     @@@@                    @@@@                                                          ||");
		System.out.println("||                                                                                                                                           ||");
		System.out.println("||      __          __  _                            _          _____       _ _                        ____ _        _   _                   ||");
		System.out.println("||      \\ \\        / / | |                          | |        |  __ \\     (_) |                      / ___| |      | | (_)                  ||");
		System.out.println("||       \\ \\  /\\  / /__| | ___ ___  _ __ ___   ___  | |_ ___   | |__) |__ _ _| |_      ____ _ _   _  | (__ | |_ __ _| |_ _  ___  _ __        ||");
		System.out.println("||        \\ \\/  \\/ / _ \\ |/ __/ _ \\| '_ ` _ \\ / _ \\ | __/ _ \\  |  _  /  _` | | \\ \\ /\\ / / _` | | | |  \\__ \\| __/ _` | __| |/ _ \\| '_ \\       ||");
		System.out.println("||         \\  /\\  /  __/ | (_| (_) | | | | | |  __/ | || (_) | | | \\ \\ (_| | | |\\ v  v / (_| | |_| |  ___) | || (_| | |_| | (_) | | | |      ||");
		System.out.println("||          \\/  \\/ \\___|_|\\___\\___/|_| |_| |_|\\___|  \\__\\___/  |_|  \\_\\__,_|_|_| \\_/\\_/ \\__,_|\\__, | |____/ \\__\\__,_|\\__|_|\\___/|_| |_|      ||");
		System.out.println("||                                                                                             __/ |                                         ||");
		System.out.println("||                                                                                            |___/                                          ||");
		System.out.println("===============================================================================================================================================");
		System.out.println();
		System.out.println();
		System.out.print("          Enter Date: ");
		String date=input.next();
		System.out.print("          Enter Day : ");
		String day=input.next();
		System.out.println();
		System.out.println();
		System.out.println("                                                         ___ _        _   _                                                                    ");
		System.out.println("                                                        / __| |_ __ _| |_(_)___ _ _                                                            ");
		System.out.println("                                                        \\__ \\  _/ _' |  _| / _ \\ ' \\                                                           ");
		System.out.println("                                                        |___/\\__\\__,_|\\__|_\\___/_||_|                                                          ");
		System.out.println();
		System.out.println("                                                       ===============================                                                         ");
		System.out.print("          From: ");
		String from=input.next();
		System.out.print("          To  : ");
		String to=input.next();
		System.out.println();
		System.out.println();
		System.out.println("                                                           _____         _                                                                     ");
		System.out.println("                                                          |_   _| _ __ _(_)_ _  ___                                                            ");
		System.out.println("                                                            | || '_/ _' | | ' \\(_-<                                                            ");
		System.out.println("                                                            |_||_| \\__,_|_|_||_/__/                                                            ");
		System.out.println();
		System.out.println("                                                       ===============================                                                         ");
		System.out.println();
		System.out.println();
		System.out.println("           ____                   __           ___           _                                                                                  ");
		System.out.println("          / __/__ ___ _  _  _____/ /______ _  / _ \\___ _  __(_)                                                                                 ");
		System.out.println("         _\\ \\/ _ '/  ' \\/ // / _  / __/ _ '/ / // / -_) |/ / /                                                                                  ");
		System.out.println("        /___/\\_,_/_/_/_/\\_,_/\\_,_/_/  \\_,_/ /____/\\__/|___/_/                                                                                   ");
		System.out.println();
		System.out.println();
		System.out.println("        Arrival-Time  : 4.50am");
		System.out.println();
		System.out.println("        Departure-Time: 5.00am");
		System.out.println();
		System.out.println();
		System.out.println("           ____                   _ __                                                                                                          ");
		System.out.println("          / __/__ ____ ____ _____(_) /_____ _                                                                                                   ");
		System.out.println("         _\\ \\/ _ '/ _ '/ _ '/ __/ /  '_/ _ '/                                                                                                   ");
		System.out.println("        /___/\\_,_/\\_, /\\_,_/_/ /_/_/\\_\\\\_,_/                                                                                                    ");
		System.out.println("                 /___/                                                                                                                          ");
		System.out.println();
		System.out.println("        Arrival-Time  : 5.55am");
		System.out.println();
		System.out.println("        Deparure-Time : 6.00am");
		System.out.println();
		System.out.println();
		System.out.println("           ___       __                    __ __                    _                                                                           ");
		System.out.println("          / _ \\__ __/ /  __ _____  __ __  / //_/_ ____ _  ___ _____(_)                                                                          ");
		System.out.println("         / , _/ // / _ \\/ // / _ \\/ // / / ,< / // /  ' \\/ _ '/ __/ /                                                                           ");
		System.out.println("        /_/|_|\\_,_/_//_/\\_,_/_//_/\\_,_/ /_/|_|\\_,_/_/_/_/\\_,_/_/ /_/                                                                            ");
		System.out.println();
		System.out.println();
		System.out.println("        Arrival-Time  : 6.55am");
		System.out.println();
		System.out.println("        Deparure-Time : 7.00am");
		System.out.println();
		System.out.println();
		System.out.println("          _____     __       __ __                    _                                                                                         ");
		System.out.println("         / ___/__ _/ /_ __  / //_/_ ____ _  ___ _____(_)                                                                                        ");
		System.out.println("        / (_ / _ '/ / // / / ,< / // /  ' \\/ _ '/ __/ /                                                                                         ");
		System.out.println("        \\___/\\_,_/_/\\_,_/ /_/|_|\\_,_/_/_/_/\\_,_/_/ /_/                                                                                          ");
		System.out.println();
		System.out.println();
		System.out.println("        Arrival-Time  : 7.20am");
		System.out.println();
		System.out.println("        Deparure-Time : 7.25am");
		System.out.println();
		System.out.println();
		System.out.println("           ___         _               __         ___         _ _      _                                                                        ");
		System.out.println("          / _ \\___ _  (_)__ ________ _/ /____ _  / _ \\___ _  (_|_)__  (_)                                                                       ");
		System.out.println("         / , _/ _ '/ / / _ '/ __/ _ '/ __/ _ '/ / , _/ _ '/ / / / _ \\/ /                                                                        ");
		System.out.println("        /_/|_|\\_,_/_/ /\\_,_/_/  \\_,_/\\__/\\_,_/ /_/|_|\\_,_/_/ /_/_//_/_/                                                                         ");
		System.out.println("                  ---                                    ---                                                                                    ");
		System.out.println();
		System.out.println("        Arrival-Time  : 10.20am");
		System.out.println();
		System.out.println("        Deparure-Time : 10.25am");
		System.out.println();
		System.out.println();
		System.out.println("================================================================================================================================================");
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println("                                        +---------------------------------------------------------------------+                                 ");
		System.out.println("                                        |  ___      _ _                    ___       _        _   _           |                                 ");
		System.out.println("                                        | | _ \\__ _(_) |_ __ ____ _ _  _  / __| __ _| |_ __ _| |_(_)___ _ _   |                                 ");
		System.out.println("                                        | |   / _' | | \\ V  V / _' | || | \\__ \\/ _' |  _/ _' |  _| / _ \\ ' \\  |                                 ");
		System.out.println("                                        | |_|_\\__,_|_|_|\\_/\\_/\\__,_|\\_, | |___/\\__,_|\\__\\__,_|\\__|_\\___/_||_| |                                 ");
		System.out.println("                                        |                           |__/                                      |                                 ");
		System.out.println("                                        |                                                                     |                                 ");
		System.out.println("                                        |                                                                     |                                 ");
		System.out.println("                                        | Day : "+day+"                                    Date: "+date+"  |                                 ");
		System.out.println("                                        | From: "+from+"                                       To  : "+to+"     |                                 ");
		System.out.println("                                        |                                                                     |                                 ");
		System.out.println("                                        +--------------------------+---------------------+--------------------+                                 ");
		System.out.println("                                        |          Train           |    Arrival Time     |    Departure Time  |                                 ");
		System.out.println("                                        +--------------------------+---------------------+--------------------+                                 ");
		System.out.println("                                        |                          |                     |                    |                                 ");
		System.out.println("                                        | Samudra Devi             |       4.50am        |       5.00am       |                                 ");
		System.out.println("                                        |                          |                     |                    |                                 ");
		System.out.println("                                        | Sagarika                 |       5.55am        |       6.00am       |                                 ");
		System.out.println("                                        |                          |                     |                    |                                 ");
		System.out.println("                                        | Ruhunu Kumari            |       6.55am        |       7.00am       |                                 ");
		System.out.println("                                        |                          |                     |                    |                                 ");
		System.out.println("                                        | Galu Kumari              |       7.20am        |       7.25am       |                                 ");
		System.out.println("                                        |                          |                     |                    |                                 ");
		System.out.println("                                        | Rajarata Rajini          |       10.20am       |       10.30am      |                                 ");
		System.out.println("                                        |                          |                     |                    |                                 ");
		System.out.println("                                        +--------------------------+---------------------+--------------------+                                 ");
	}
}
